version: '3.8'

services:
  app:
    image: php:8.1-apache
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - ./app/public:/var/www/html 
      - ./app/src:/var/www/app 
      - ./config:/var/www/config 
      - ./app/routes:/var/www/html/routes
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql &&
               a2enmod rewrite &&
               apache2-foreground"
    depends_on:
      - db
    restart: always
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: webapp            # Initial database name
      MYSQL_ROOT_PASSWORD: mateo        # Root password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql          # Persistent database storage
      - ./config/dbsetup.sql:/docker-entrypoint-initdb.d/dbsetup.sql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db                      # MySQL service name
      MYSQL_ROOT_PASSWORD: mateo        # Root password to access db
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge